# !!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !!! Welcome to AutoSiril !!!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!
# 
# The program you are using now is a GUI front for Siril's excellent Midi 2 VT
# engine, affectionately known as AutoSiril... 
# 
# The original AutoSiril engine comes with its own instructions, so these details
# will mainly concern themselves with the GUI Frontend being used here.
# 
# Running this program for the first time will autogenerate this file that you
# are now reading.  This file, module_template.rb, actually consists of 3 files:
# 
# 1) A brief help guide for usage (your reading it)
# 2) A list of default parameters & file extensions for Autosiril output.
# 3) The default module_header template for the Vortex Tracker song layout.
# 
# This file will be automatically created in the directory of the main program, 
# if it be missing.  If the file is present, then the main program will take its
# parameters directly from it.
# 
# Thus, changes to this main file, will alter the default settings of AutoSiril.
# And if you mess up the settings, you can simply delete the file, run the main
# program, and another copy will be autogenerated for reediting again...
# 
# ON CHANGING THE DEFAULT PARAMETERS:
# ===================================
# 
# During conversion, this program is designed to spit out a number of variations
# of your outputed song, each with their own filename, each according to their
# own set of parameters. How many variations this program spits out per song, is 
# dependent on how many entries are listed in the parameter list.
# 
# The parameter list is easy to edit, and consists of the following format:
# 
#                   FileExtension : parameters
# 
# NOTE: 
# - The FileExtension is bolted onto the end of the filename to convert
# - The Colon [:] acts as a separator between the two items of data (no spaces)
# - The parameters are passed to the AutoSiril program via the GUI front end.
# 
# The Parameter list now follows:
# 
################################################################################

def PARAMETER_LIST()
"
_VT01.txt:5du-4du+-3du+,1p,2m 8 6 12 0 64 2 24
_VT02.txt:5m-2p,4d-3me,1p
_VT03.txt:2me,3m,4m 8 6 12 0 64 2 24
_VT04.txt:2m,7d-2me,3pw 8 6 12 0 64 2 24
_VT05.txt:2me,3m-7m-6p+,4m-5m+ 8 6 12 0 64 2 24
_VT06.txt:2me[2f]-6p[3]+,3m[1e]-7m[6d]-6p[3]+-2mew+,4m[3c]-5m[2b]+-2me+ 8 6 12 0 64 2 24
_VT07.txt:1d-2me-3p,4m[uf]-5m[2]+,5m[6]-6me[2]+-3p[3]+-2mew+ 8 6 12 0 64 2 6
_VT08.txt:9d-10d-11d-12d, 4p-5m-7m, 6m-8m | 1me, 2me, 3p
"
end

################################################################################

def module_header(title,play_order,ornaments_txt)
	"[Module]
VortexTrackerII=0
Version=3.5
Title=#{title}
Author=oisee/siril^4d #{Time.new.strftime("%Y.%m.%d")}
NoteTable=4
ChipFreq=1750000
Speed=4
PlayOrder=#{play_order}
ArgList=#{ARGV.join(' ')}

#{ornaments_txt}

[Sample1]
TnE +000_ +00_ F_
TnE +000_ +00_ F_
TnE +000_ +00_ F_
TnE +000_ +00_ D_
TnE +000_ +00_ B_
TnE +000_ +00_ B_ L

[Sample2]
TnE +000_ +00_ F_ L

[Sample3]
TnE +001_ +00_ F_
TnE +002_ +00_ F_
TnE +001_ +00_ E_
TnE +002_ +00_ E_
TnE +000_ +00_ E_ L
TnE -001_ +00_ E_
TnE -002_ +00_ E_
TnE -001_ +00_ E_
TnE +000_ +00_ E_
TnE +001_ +00_ E_
TnE +002_ +00_ E_
TnE +001_ +00_ E_

[Sample4]
TnE +002_ +00_ D_
TnE +002_ +00_ D_
TnE +002_ +00_ C_
TnE +002_ +00_ B_
TnE +002_ +00_ A_ L
TnE +002_ +00_ A_
TnE +002_ +00_ A_
TnE +002_ +00_ A_
TnE +002_ +00_ A_
TnE +002_ +00_ A_
TnE +002_ +00_ A_
TnE +002_ +00_ A_

[Sample5]
TnE +000_ +00_ F_
TnE +000_ +00_ F_
tne +000_ +00_ 0_ L

[Sample6]
TnE -001_ +00_ F_ L

[Sample7]
TnE +006_ +00_ F_ L

[Sample8]
tNe +000_ +00_ F_
tNe +000_ +00_ B_
tNe +000_ +00_ 7_
tNe +000_ +00_ 6- L

[Sample9]
TnE +080_ +00_ F_
TnE +100_ +00_ E_
TnE +180_ +00_ E_
TnE +200_ +00_ E_
TnE +240_ +00_ D_
TnE +280_ +00_ D_
TnE +2C0_ +00_ D_
TnE +300_ +00_ C_
TnE +300_ +00_ C_
TnE +340_ +00_ C_
TnE +340_ +00_ C_
TnE +380_ +00_ B_
TnE +380_ +00_ B_
TnE +400_ +00_ B_
TnE +400_ +00_ B_
TnE +480_ +00_ A_
TnE +500_ +00_ 9_
TnE +580_ +00_ 7_
TnE +600_ +00_ 4_
TnE +680_ +00_ 1_
TnE +000_ +00_ 0_ L

[Sample10]
Tne +1C0_ +00_ F_
Tne +280_ +00_ E_
Tne +380_ +00_ C_
Tne +440_ +00_ A_
Tne +480_ +00_ 8_
TnE +000_ +00_ 0_ L

[Sample11]
TNe +200_ -0A_ F_
tNe +000_ +0F_ A_
TNe +200_ -07_ E_
tNe +000_ +0E_ B- L

[Sample12]
TNE +0A0_ +05_ F_
TNE +140_ +02_ D_
TNE +140_ +02_ B_
TNE +100_ +00_ A_ L
TNE +140_ +00_ A_
TNE +200_ +00_ A-

[Sample13]
Tne +200_ +00_ F_
Tne +2C0_ +00_ F_
Tne +380_ +00_ E_
Tne +500_ +00_ C_
Tne +520_ +00_ 9_
tne +000_ +00_ 0_ L

[Sample14]
TNE -100_ +00_ F_
TNE -100_ +00_ D_
TNE -100_ +00_ A_
TNE -100_ +00_ 5_
tne +000_ +00_ 0_ L

[Sample15]
TNE -100_ +00_ 5_
TNE -100_ +00_ 8_
TNE -100_ +00_ B_
TNE -100_ +00_ F_
TNe -100_ +00_ 9- L

[Sample16]
TnE +000_ +00_ C_
TnE +000_ +00_ E_
TnE +000_ +00_ F_
TnE +000_ +00_ F_
TnE +000_ +00_ E_
TnE +000_ +00_ D_
TnE +000_ +00_ C_
TnE +000_ +00_ C_ L
TnE +001_ +00_ C_
TnE +002_ +00_ C_
TnE +003_ +00_ C_
TnE +001_ +00_ C_
TnE +000_ +00_ C_
TnE -001_ +00_ C_
TnE -002_ +00_ C_
TnE -003_ +00_ C_
TnE -001_ +00_ C_
TnE +000_ +00_ C_
TnE +000_ +00_ C_

[Sample17]
Tne +1C0_ +00_ F_
Tne +280_ +00_ D_
Tne +380_ +00_ 7_
TNE +000_ +00_ 0_ L

[Sample18]
TnE -00C_ +00_ 0_ L

[Sample19]
TNe +000_ +00_ F_
TNe +000_ +00_ C_
TNe +000_ +00_ 6_
TNe +000_ +01_ A- L

[Sample20]
TNE +140_ +00_ F_
tNE +000_ +00_ B- L

[Sample21]
tNE +000_ +00_ D_
tNE +000_ +00_ 8_
tNE +000_ +00_ 1_
TNE +000_ +00_ 0_ L

[Sample22]
TnE +000_ +00_ D_ L
TnE +000_ +00_ D_
tne +000_ +00_ 9_
tne +000_ +00_ 9_
TnE +000_ +00_ D_
TnE +000_ +00_ D_
tne +000_ +00_ 9_
tne +000_ +00_ 9_
TnE +000_ +00_ D_
TnE +000_ +00_ D_
TnE +000_ +00_ D_
TnE +000_ +00_ D_
TnE +000_ +00_ D_
TnE +000_ +00_ D_
tne +000_ +00_ 9_
tne +000_ +00_ 9_

[Sample23]
TnE +000_ +00_ F_ L
TnE +010_ +01_ F_
TnE +010_ +01_ F_
TnE +010_ +01_ F_
TnE +010_ +01_ F_
TnE +000_ +00_ F_
TnE +000_ +00_ F_
TnE -010_ -01_ F_
TnE -010_ -01_ F_
TnE -010_ -01_ F_
TnE -010_ -01_ F_
TnE +000_ +00_ F_

[Sample24]
TNe +000_ -01_ C_
TNe +000_ -01_ D_
TNe +000_ -01_ E_
TNe +000_ -01_ F_
TNe +000_ -01_ F_
TNe +000_ -01_ F_
TNe +000_ -01_ F_
TNe +000_ -01_ F_
TNe +000_ -01_ E_
TNe +000_ -01_ E_
TNe +000_ -01_ E_
TNe +000_ -01_ F_
TNe +000_ -01_ F_ L

[Sample25]
TNE +000_ +00_ F_
TNE +000_ +00_ F_ L
TNE +000_ +00_ F_
TNE +000_ +00_ F_
TNE +000_ +00_ F-

[Sample26]
tne +000_ +00_ 0_ L

[Sample27]
TnE +100_ +05_ F_
TnE +200_ +02_ A_
TnE +300_ +02_ 7_
TNE +400_ +00_ 3- L

[Sample28]
tne +000_ +00_ 0_ L

[Sample29]
tnE +000_ +00_ 0_ L

[Sample30]
TNE +000_ +00_ C+ L

[Sample31]
TNe +1C0_ +00_ F_
Tne +280_ +00_ E_
Tne +380_ +00_ C_
Tne +440_ +00_ A_
Tne +480_ +00_ 8_
TnE +000_ +00_ 0_ L"
end