; AKG format, v1.0.

; Generated by Arkos Tracker 2.

pacman_Start
pacman_StartDisarkGenerateExternalLabel

pacman_DisarkByteRegionStart0
	db "AT20"
pacman_DisarkPointerRegionStart1
	dw pacman_ArpeggioTable	; The address of the Arpeggio table.
	dw pacman_PitchTable	; The address of the Pitch table.
	dw pacman_InstrumentTable	; The address of the Instrument table.
	dw pacman_EffectBlockTable	; The address of the Effect Block table.
pacman_DisarkPointerRegionEnd1


; The addresses of each Subsong:
pacman_DisarkPointerRegionStart2
	dw pacman_Subsong0_Start
	dw pacman_Subsong1_Start
pacman_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
pacman_ArpeggioTable
pacman_DisarkPointerRegionStart3
pacman_DisarkPointerRegionEnd3

; Declares all the Pitches.
pacman_PitchTable
pacman_DisarkPointerRegionStart4
pacman_DisarkPointerRegionEnd4

; Declares all the Instruments.
pacman_InstrumentTable
pacman_DisarkPointerRegionStart5
	dw pacman_EmptyInstrument
	dw pacman_Instrument1
pacman_DisarkPointerRegionEnd5

pacman_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
pacman_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

pacman_Instrument1
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
pacman_EffectBlockTable
pacman_DisarkPointerRegionStart6
	dw pacman_EffectBlock_P4P7	; Index 0
	dw pacman_EffectBlock_P4P0	; Index 1
	dw pacman_EffectBlock_P5P0P8	; Index 2
pacman_DisarkPointerRegionEnd6

pacman_EffectBlock_P4P0
	db 4, 0
pacman_EffectBlock_P4P7
	db 4, 7
pacman_EffectBlock_P5P0P8
	db 5, 0, 8

pacman_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
pacman_Subsong0_DisarkByteRegionStart0
pacman_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 0	; End index (>=0).
	db 3	; Initial speed (>=0).
	db 17	; Base note index (>=0).

pacman_Subsong0_Linker
pacman_Subsong0_DisarkPointerRegionStart1
; Position 0
pacman_Subsong0_Linker_Loop
	dw pacman_Subsong0_Track0
	dw pacman_Subsong0_Track1
	dw pacman_Subsong0_Track2
	dw pacman_Subsong0_LinkerBlock0

pacman_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
pacman_Subsong0_DisarkWordForceReference2
	dw pacman_Subsong0_Linker_Loop

pacman_Subsong0_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
pacman_Subsong0_DisarkWordForceReference3
	dw pacman_Subsong0_SpeedTrack0	; SpeedTrack address.
pacman_Subsong0_DisarkWordForceReference4
	dw pacman_Subsong0_EventTrack0	; EventTrack address.

pacman_Subsong0_Track0
	db 234
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 54
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 54
	db 49
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 47
	db 60	; Waits for 1 line.

	db 55
	db 50
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 60	; Waits for 1 line.

	db 54
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 54
	db 49
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 46
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 46
	db 47
	db 48
	db 60	; Waits for 1 line.

	db 48
	db 49
	db 50
	db 60	; Waits for 1 line.

	db 50
	db 51
	db 52
	db 60	; Waits for 1 line.

	db 54
	db 61, 127	; Waits for 128 lines.


pacman_Subsong0_Track1
	db 210
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 82
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 94
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 82
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 82
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 19
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 82
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 95
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 83
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 83
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 18
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 83
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 94
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 82
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 82
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 13
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 15
	db 60	; Waits for 1 line.

	db 77
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 81
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 18
	db 60	; Waits for 1 line.

	db 81
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


pacman_Subsong0_Track2
	db 61, 127	; Waits for 128 lines.


; The speed tracks
pacman_Subsong0_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
pacman_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

pacman_Subsong0_DisarkByteRegionEnd0
; Subsong 1
; ----------------------
pacman_Subsong1_DisarkByteRegionStart0
pacman_Subsong1_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 0	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 4	; Base note index (>=0).

pacman_Subsong1_Linker
pacman_Subsong1_DisarkPointerRegionStart1
; Position 0
pacman_Subsong1_Linker_Loop
	dw pacman_Subsong1_Track0
	dw pacman_Subsong1_Track1
	dw pacman_Subsong1_Track2
	dw pacman_Subsong1_LinkerBlock0

pacman_Subsong1_DisarkPointerRegionEnd1
	dw 0	; Loop.
pacman_Subsong1_DisarkWordForceReference2
	dw pacman_Subsong1_Linker_Loop

pacman_Subsong1_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
pacman_Subsong1_DisarkWordForceReference3
	dw pacman_Subsong1_SpeedTrack0	; SpeedTrack address.
pacman_Subsong1_DisarkWordForceReference4
	dw pacman_Subsong1_EventTrack0	; EventTrack address.

pacman_Subsong1_Track0
	db 165
	db 1	; New Instrument (1).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 37
	db 37
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 37
	db 37
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 37
	db 41
	db 42
	db 43
	db 44
	db 37
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 37
	db 37
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 37
	db 37
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 37
	db 41
	db 42
	db 43
	db 44
	db 37
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 37
	db 37
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 37
	db 37
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 37
	db 41
	db 42
	db 43
	db 44
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 44
	db 43
	db 42
	db 40
	db 37
	db 35
	db 60	; Waits for 1 line.

	db 36
	db 60	; Waits for 1 line.

	db 37
	db 61, 127	; Waits for 128 lines.


pacman_Subsong1_Track1
	db 177
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 46
	db 44
	db 49
	db 49
	db 60	; Waits for 1 line.

	db 53
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 49
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 46
	db 44
	db 49
	db 49
	db 60	; Waits for 1 line.

	db 46
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 49
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 46
	db 44
	db 49
	db 49
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 54
	db 60	; Waits for 1 line.

	db 55
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 54
	db 60	; Waits for 1 line.

	db 52
	db 60	; Waits for 1 line.

	db 49
	db 60	; Waits for 1 line.

	db 52
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 49
	db 61, 127	; Waits for 128 lines.


pacman_Subsong1_Track2
	db 61, 127	; Waits for 128 lines.


; The speed tracks
pacman_Subsong1_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
pacman_Subsong1_EventTrack0
	db 255	; Wait for 128 lines.

pacman_Subsong1_DisarkByteRegionEnd0
