
MUSICDATA:
                          DEFB 96   ; Loop start point * 2
                          DEFB 98   ; Song Length * 2
PATTERNDATA:              DEFW PAT0
                          DEFW PAT0
                          DEFW PAT1
                          DEFW PAT1
                          DEFW PAT2
                          DEFW PAT1
                          DEFW PAT0
                          DEFW PAT3
                          DEFW PAT4
                          DEFW PAT5
                          DEFW PAT6
                          DEFW PAT7
                          DEFW PAT4
                          DEFW PAT5
                          DEFW PAT6
                          DEFW PAT8
                          DEFW PAT9
                          DEFW PAT10
                          DEFW PAT11
                          DEFW PAT12
                          DEFW PAT13
                          DEFW PAT14
                          DEFW PAT15
                          DEFW PAT16
                          DEFW PAT17
                          DEFW PAT17
                          DEFW PAT18
                          DEFW PAT18
                          DEFW PAT19
                          DEFW PAT19
                          DEFW PAT18
                          DEFW PAT20
                          DEFW PAT4
                          DEFW PAT5
                          DEFW PAT6
                          DEFW PAT7
                          DEFW PAT4
                          DEFW PAT5
                          DEFW PAT6
                          DEFW PAT21
                          DEFW PAT0
                          DEFW PAT0
                          DEFW PAT1
                          DEFW PAT1
                          DEFW PAT2
                          DEFW PAT1
                          DEFW PAT0
                          DEFW PAT25
                          DEFW PAT26

; *** Pattern data consists of pairs of note values CH1,CH2 with a single $0 to
; *** mark the end of the pattern, and $01 for a rest
PAT0:
                          DEFB 3  ; Pattern tempo
                          DEFB 1,81
                          DEFB 1,1
                          DEFB 1,88
                          DEFB 81,1
                          DEFB 1,93
                          DEFB 88,1
                          DEFB 1,96
                          DEFB 93,1
                          DEFB 1,100
                          DEFB 96,1
                          DEFB 1,96
                          DEFB 100,1
                          DEFB 1,93
                          DEFB 96,1
                          DEFB 1,88
                          DEFB 93,1
                          DEFB $0
PAT1:
                          DEFB 3  ; Pattern tempo
                          DEFB 1,79
                          DEFB 1,1
                          DEFB 1,86
                          DEFB 79,1
                          DEFB 1,91
                          DEFB 86,1
                          DEFB 1,95
                          DEFB 91,1
                          DEFB 1,98
                          DEFB 95,1
                          DEFB 1,95
                          DEFB 98,1
                          DEFB 1,91
                          DEFB 95,1
                          DEFB 1,86
                          DEFB 91,1
                          DEFB $0
PAT2:
                          DEFB 3  ; Pattern tempo
                          DEFB 1,77
                          DEFB 1,1
                          DEFB 1,84
                          DEFB 77,1
                          DEFB 1,89
                          DEFB 84,1
                          DEFB 1,93
                          DEFB 89,1
                          DEFB 1,96
                          DEFB 93,1
                          DEFB 1,93
                          DEFB 96,1
                          DEFB 1,89
                          DEFB 93,1
                          DEFB 1,77
                          DEFB 89,1
                          DEFB $0
PAT3:
                          DEFB 3  ; Pattern tempo
                          DEFB 1,81
                          DEFB 1,1
                          DEFB 81,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 1,81
                          DEFB 1,1
                          DEFB 81,1
                          DEFB 1,1
                          DEFB 1,79
                          DEFB 1,1
                          DEFB 79,1
                          DEFB 1,95
                          DEFB $0
PAT4:
                          DEFB 3  ; Pattern tempo
                          DEFB 81,96
                          DEFB 1,1
                          DEFB 91,1
                          DEFB 93,88
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 79,88
                          DEFB 1,1
                          DEFB 81,1
                          DEFB 1,1
                          DEFB 91,1
                          DEFB 93,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 79,1
                          DEFB 1,1
                          DEFB 81,96
                          DEFB 1,1
                          DEFB 91,1
                          DEFB 93,88
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 79,88
                          DEFB 1,1
                          DEFB 81,96
                          DEFB 1,1
                          DEFB 91,1
                          DEFB 93,95
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 79,93
                          DEFB 1,1
                          DEFB $0
PAT5:
                          DEFB 3  ; Pattern tempo
                          DEFB 79,95
                          DEFB 1,1
                          DEFB 89,1
                          DEFB 91,86
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 77,86
                          DEFB 1,1
                          DEFB 79,1
                          DEFB 1,1
                          DEFB 89,1
                          DEFB 91,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 77,1
                          DEFB 1,1
                          DEFB 79,93
                          DEFB 1,95
                          DEFB 89,1
                          DEFB 91,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 77,89
                          DEFB 1,91
                          DEFB 79,93
                          DEFB 1,1
                          DEFB 89,1
                          DEFB 91,91
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 77,86
                          DEFB 1,1
                          DEFB $0
PAT6:
                          DEFB 3  ; Pattern tempo
                          DEFB 77,93
                          DEFB 1,1
                          DEFB 88,1
                          DEFB 89,84
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 76,84
                          DEFB 1,1
                          DEFB 77,1
                          DEFB 1,1
                          DEFB 88,1
                          DEFB 89,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 76,1
                          DEFB 1,1
                          DEFB 77,93
                          DEFB 1,1
                          DEFB 88,1
                          DEFB 89,84
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 76,84
                          DEFB 1,95
                          DEFB 77,96
                          DEFB 1,1
                          DEFB 88,1
                          DEFB 89,1
                          DEFB 1,81
                          DEFB 1,1
                          DEFB 76,86
                          DEFB 1,1
                          DEFB $0
PAT7:
                          DEFB 3  ; Pattern tempo
                          DEFB 79,88
                          DEFB 1,1
                          DEFB 89,1
                          DEFB 91,86
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 77,84
                          DEFB 1,1
                          DEFB 79,84
                          DEFB 1,1
                          DEFB 89,1
                          DEFB 91,86
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 77,88
                          DEFB 1,1
                          DEFB 79,86
                          DEFB 1,1
                          DEFB 89,1
                          DEFB 91,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 77,1
                          DEFB 1,1
                          DEFB 79,1
                          DEFB 1,1
                          DEFB 89,1
                          DEFB 91,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 77,1
                          DEFB 1,95
                          DEFB $0
PAT8:
                          DEFB 3  ; Pattern tempo
                          DEFB 79,88
                          DEFB 1,1
                          DEFB 89,1
                          DEFB 91,86
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 77,84
                          DEFB 1,1
                          DEFB 79,84
                          DEFB 1,1
                          DEFB 89,1
                          DEFB 91,86
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 77,88
                          DEFB 1,1
                          DEFB 79,91
                          DEFB 1,1
                          DEFB 89,1
                          DEFB 91,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 77,1
                          DEFB 1,1
                          DEFB 79,1
                          DEFB 1,1
                          DEFB 89,1
                          DEFB 91,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 77,1
                          DEFB 1,1
                          DEFB $0
PAT9:
                          DEFB 3  ; Pattern tempo
                          DEFB 84,81
                          DEFB 84,81
                          DEFB 84,1
                          DEFB 1,1
                          DEFB 84,1
                          DEFB 1,1
                          DEFB 84,81
                          DEFB 84,81
                          DEFB 84,1
                          DEFB 1,1
                          DEFB 84,1
                          DEFB 1,1
                          DEFB 84,1
                          DEFB 1,1
                          DEFB 84,1
                          DEFB 1,1
                          DEFB $0
PAT10:
                          DEFB 3  ; Pattern tempo
                          DEFB 84,81
                          DEFB 84,81
                          DEFB 84,1
                          DEFB 1,1
                          DEFB 84,1
                          DEFB 1,1
                          DEFB 84,81
                          DEFB 84,81
                          DEFB 84,1
                          DEFB 1,93
                          DEFB 84,95
                          DEFB 1,1
                          DEFB 84,96
                          DEFB 1,1
                          DEFB 84,95
                          DEFB 1,1
                          DEFB $0
PAT11:
                          DEFB 3  ; Pattern tempo
                          DEFB 91,79
                          DEFB 1,79
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 95,1
                          DEFB 1,1
                          DEFB 95,79
                          DEFB 95,79
                          DEFB 95,1
                          DEFB 1,1
                          DEFB 95,1
                          DEFB 1,1
                          DEFB 95,1
                          DEFB 1,1
                          DEFB 95,1
                          DEFB 1,1
                          DEFB $0
PAT12:
                          DEFB 3  ; Pattern tempo
                          DEFB 95,79
                          DEFB 95,79
                          DEFB 95,1
                          DEFB 1,1
                          DEFB 95,1
                          DEFB 1,1
                          DEFB 95,79
                          DEFB 95,79
                          DEFB 95,1
                          DEFB 1,91
                          DEFB 95,93
                          DEFB 1,1
                          DEFB 95,93
                          DEFB 1,1
                          DEFB 95,91
                          DEFB 1,1
                          DEFB $0
PAT13:
                          DEFB 3  ; Pattern tempo
                          DEFB 93,77
                          DEFB 1,77
                          DEFB 84,1
                          DEFB 1,1
                          DEFB 84,1
                          DEFB 1,1
                          DEFB 84,77
                          DEFB 84,77
                          DEFB 84,1
                          DEFB 1,1
                          DEFB 84,1
                          DEFB 1,1
                          DEFB 84,1
                          DEFB 1,1
                          DEFB 84,1
                          DEFB 1,1
                          DEFB $0
PAT14:
                          DEFB 3  ; Pattern tempo
                          DEFB 84,77
                          DEFB 84,77
                          DEFB 84,1
                          DEFB 1,1
                          DEFB 84,1
                          DEFB 1,1
                          DEFB 84,77
                          DEFB 84,77
                          DEFB 84,1
                          DEFB 1,1
                          DEFB 84,89
                          DEFB 1,1
                          DEFB 84,91
                          DEFB 1,1
                          DEFB 84,93
                          DEFB 1,1
                          DEFB $0
PAT15:
                          DEFB 3  ; Pattern tempo
                          DEFB 91,79
                          DEFB 1,79
                          DEFB 91,91
                          DEFB 1,1
                          DEFB 91,1
                          DEFB 1,1
                          DEFB 91,79
                          DEFB 1,79
                          DEFB 91,91
                          DEFB 1,1
                          DEFB 91,1
                          DEFB 1,1
                          DEFB 91,1
                          DEFB 1,1
                          DEFB 91,1
                          DEFB 1,1
                          DEFB $0
PAT16:
                          DEFB 3  ; Pattern tempo
                          DEFB 79,91
                          DEFB 79,1
                          DEFB 91,1
                          DEFB 1,1
                          DEFB 91,1
                          DEFB 1,1
                          DEFB 79,1
                          DEFB 79,1
                          DEFB 91,1
                          DEFB 1,1
                          DEFB 91,79
                          DEFB 1,1
                          DEFB 91,79
                          DEFB 1,1
                          DEFB 91,79
                          DEFB 1,1
                          DEFB $0
PAT17:
                          DEFB 3  ; Pattern tempo
                          DEFB 93,81
                          DEFB 93,81
                          DEFB 91,1
                          DEFB 84,93
                          DEFB 1,81
                          DEFB 1,1
                          DEFB 81,93
                          DEFB 81,93
                          DEFB 81,1
                          DEFB 1,1
                          DEFB 79,83
                          DEFB 1,93
                          DEFB 84,81
                          DEFB 1,1
                          DEFB 79,83
                          DEFB 1,1
                          DEFB $0
PAT18:
                          DEFB 3  ; Pattern tempo
                          DEFB 91,79
                          DEFB 91,79
                          DEFB 89,1
                          DEFB 95,91
                          DEFB 1,79
                          DEFB 1,1
                          DEFB 79,91
                          DEFB 79,91
                          DEFB 79,1
                          DEFB 1,1
                          DEFB 77,93
                          DEFB 1,91
                          DEFB 95,79
                          DEFB 1,1
                          DEFB 77,93
                          DEFB 1,1
                          DEFB $0
PAT19:
                          DEFB 3  ; Pattern tempo
                          DEFB 89,77
                          DEFB 89,77
                          DEFB 88,1
                          DEFB 93,89
                          DEFB 1,77
                          DEFB 1,1
                          DEFB 77,89
                          DEFB 77,89
                          DEFB 77,1
                          DEFB 1,1
                          DEFB 76,91
                          DEFB 1,89
                          DEFB 93,77
                          DEFB 1,1
                          DEFB 76,91
                          DEFB 1,1
                          DEFB $0
PAT20:
                          DEFB 3  ; Pattern tempo
                          DEFB 91,79
                          DEFB 91,79
                          DEFB 91,1
                          DEFB 89,91
                          DEFB 79,79
                          DEFB 1,1
                          DEFB 79,93
                          DEFB 79,95
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 76,1
                          DEFB 1,1
                          DEFB 79,1
                          DEFB 1,1
                          DEFB 83,1
                          DEFB 1,95
                          DEFB $0
PAT21:
                          DEFB 3  ; Pattern tempo
                          DEFB 79,88
                          DEFB 1,1
                          DEFB 89,1
                          DEFB 91,86
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 77,84
                          DEFB 1,1
                          DEFB 79,84
                          DEFB 1,1
                          DEFB 89,1
                          DEFB 91,86
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 77,88
                          DEFB 1,1
                          DEFB 79,91
                          DEFB 1,1
                          DEFB 89,1
                          DEFB 91,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 77,1
                          DEFB 1,1
                          DEFB 79,1
                          DEFB 1,1
                          DEFB 89,1
                          DEFB 91,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB $0
PAT25:
                          DEFB 3  ; Pattern tempo
                          DEFB 1,81
                          DEFB 1,1
                          DEFB 81,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB $0
PAT26:
                          DEFB 3  ; Pattern tempo
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB 1,1
                          DEFB $0
